# Generated by Django 4.2.27 on 2025-12-03 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Plan adı")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Fiyat (TL)"
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[("monthly", "Aylık"), ("yearly", "Yıllık")],
                        default="monthly",
                        max_length=20,
                        verbose_name="Ödeme aralığı",
                    ),
                ),
                ("features", models.JSONField(default=dict, verbose_name="Özellikler")),
                (
                    "api_calls_per_day",
                    models.IntegerField(default=10, verbose_name="Günlük API limiti"),
                ),
                (
                    "history_days",
                    models.IntegerField(default=7, verbose_name="Geçmiş veri (gün)"),
                ),
                (
                    "iyzico_product_ref",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="iyzico ürün referansı"
                    ),
                ),
                (
                    "iyzico_plan_ref",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="iyzico plan referansı"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Öne çıkan"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Planlar",
                "ordering": ["sort_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktif"),
                            ("pending", "Beklemede"),
                            ("cancelled", "İptal edildi"),
                            ("expired", "Süresi doldu"),
                            ("unpaid", "Ödenmemiş"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(verbose_name="Dönem başlangıcı"),
                ),
                ("current_period_end", models.DateTimeField(verbose_name="Dönem sonu")),
                (
                    "iyzico_subscription_ref",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="iyzico abonelik referansı",
                    ),
                ),
                (
                    "iyzico_customer_ref",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="iyzico müşteri referansı",
                    ),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(
                        default=False, verbose_name="Dönem sonunda iptal"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İptal tarihi"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="İptal nedeni"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonelik",
                "verbose_name_plural": "Abonelikler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Oluşturuldu"),
                            ("activated", "Aktifleştirildi"),
                            ("renewed", "Yenilendi"),
                            ("payment_failed", "Ödeme başarısız"),
                            ("cancelled", "İptal edildi"),
                            ("expired", "Süresi doldu"),
                            ("upgraded", "Yükseltildi"),
                            ("downgraded", "Düşürüldü"),
                        ],
                        max_length=30,
                        verbose_name="Olay tipi",
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="Veri"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonelik olayı",
                "verbose_name_plural": "Abonelik olayları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Tutar"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para birimi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Başarısız"),
                            ("refunded", "İade edildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "iyzico_payment_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="iyzico ödeme ID",
                    ),
                ),
                (
                    "iyzico_payment_transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="iyzico işlem ID"
                    ),
                ),
                (
                    "card_last_four",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Kart son 4 hane"
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Kart markası"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Fatura no"
                    ),
                ),
                ("invoice_url", models.URLField(blank=True, verbose_name="Fatura URL")),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ödeme tarihi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata mesajı"),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödeme",
                "verbose_name_plural": "Ödemeler",
                "ordering": ["-created_at"],
            },
        ),
    ]
